### PR TITLE
Added error checking.

### PR DESCRIPTION
**Pull request by sukritkalra**
Checked if the subprocess called returned an error (non zero returncode) or there was an error in calling the process (OSError).

Earlier, calling a command such as `python file_does_not_exist.py` returned a graph such as:

image3

Now, the program gracefully terminates:

`python: can't open file 'file_does_not_exist.py': [Errno 2] No such file or directory`

Similarly, if an unknown command was passed to `memplot` earlier, it used to raise an `OSError` to the user. Running something like `memplot "command_does_not_exist"` would raise a huge wall of errors to the user.

This now gracefully terminates with the error message `[Errno 2] No such file or directory`

### CODE REVIEW

**Comment by ericchiang** [comment]
This has the unfortunate side effect of not plotting anything if a correctly called process happens to crash. For example the following code won't produce a chart even though you'd still want one:

``` python
import numpy as np
import pickle

x = np.random.randn(10000,10000)
sleep(1)
pickle.dump(x,open("x.pk","w"))
raise Exception()
```

Closing for now

**Comment by sukritkalra** [comment]
I removed the lines that do not let the program plot if the script returns a non zero error code. Although, any commands that are not valid i.e. `memplot "command_does_not_exist"` still fail gracefully. Can you check this one out please? Let me know if there are some cases where this fails, too.

**Comment by ericchiang** [comment]
Couple things. First, there have been updates to the `master` branch so please sync up before issuing a pull request.

Secondly, sure `memplot "command_does_not_exist"` doesn't produce a graph but something like `memplot "python bad_file_name.py"` still does. This is an artifact of running Popen with `shell=False` so really it will only "fail gracefully" when Popen gets mad.

Seems like a better use of effort would be to figure out how to turn the `shell` argument back to `True` since this commit just alerts the user that the command is trying to use shell features anyway. Maybe aggregate the usage of all child processes?

**Comment by sukritkalra** [comment]
Turning the `shell` argument back to `True` wouldn't work, I believe, since it would start up a new shell and execute the process in it, thus resulting in an incorrect RSS value. What do you mean by aggregating the usage of all child processes? Child processes created in the shell that was invoked?

**Comment by ericchiang** [comment]
This should do it:
https://github.com/EricChiang/memplot/commit/9bc01651d16bc4e3f8553f5c70b3629b1202b738

**Comment by sukritkalra** [comment]
Ah. Nice. But, this still outputs a graph like the first post when `memplot command_does_not_exist` is entered.

**Comment by ericchiang** [comment]
It's just going to be hard to figure out if the error code is because of a mistyped command or if it's because of the command is throwing an exception (since the former produces the latter). If you can figure out a clean way to do it that's fine. But I'm skeptical that any distinction between a mistyped command and a correctly typed failing process will be arbitrary.

**Comment by sukritkalra** [comment]
Yes. I'll see if there is a clean way for this. I doubt this because of the reasons that you stated, though.

**Pull request closed without merging**
